version: '3.6'
services:
  server:
    build: .
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    entrypoint:
      - /bin/bash
      - /app/scripts/run.sh
    # links:
    #   - couchbase
